# Generated by Django 4.1.7 on 2023-04-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("redirect", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="short_link",
            old_name="full_id",
            new_name="full",
        ),
        migrations.RenameField(
            model_name="short_link",
            old_name="user_id",
            new_name="user",
        ),
    ]
